/*********************************************************************
*  #### Simple Particle Engine v3.0 (Work in progress!) ####
*  Coded by Jason Mayes 2014. www.jasonmayes.com
*  Please keep this disclaimer with my code if you use it. Thanks. :-)
*  Got feedback or questions, ask here:
*  http://plus.google.com/+JasonMayes/posts
 * Updates will be posted to this site:
 * http://www.jasonmayes.com/projects/particleEngine/
 * Or see Github:
 * https://github.com/jasonmayes/Particle-Engine
*********************************************************************/
window.requestAnimationFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(k){window.setTimeout(k,1E3/60)}}();
var jmParticleEngine=function(){function k(a,b,d,c,e,f,g,k,m,n,p,q,r){this.x=a;this.y=b;this.width=d;this.height=c;this.rotation=e;this.xVelocity=f;this.yVelocity=g;this.life=this.maxLife=k;this.growthType=m;this.r=n;this.g=p;this.b=q;this.image=r}function g(a,b,d,c){this.x=a;this.y=b;this.maxParticles=d||500;this.particles=[];this.generateParticle=c;this.emit=!1;this.images=[]}function l(a,b,d){var c={},c="string"===typeof a?document.getElementById(a):a;c.addEventListener?c.addEventListener(b,d,
!1):c.attachEvent?c.attachEvent("on"+b,d):c["on"+b]=d}function s(a,b,d,c){0!==a.rotation?(e.save(),e.translate(a.x,a.y),e.rotate(a.rotation),void 0!==c?e.drawImage(c,-b/2,-d/2,b,d):e.fillRect(-b/2,-d/2,b,d),e.restore()):void 0!==c?e.drawImage(c,a.x,a.y,b,d):e.fillRect(a.x,a.y,b,d)}function t(a){e.clearRect(0,0,f.width,f.height);a=b.length;for(var h=0,d=0;a--;){b[a].particles.length===b[a].maxParticles&&b[a].particles.shift();if(b[a].emit&&(d=b[a].maxParticles-b[a].particles.length,h=Math.ceil(.01*
d),0<d))for(d=0;d<h;)b[a].particles.push(b[a].generateParticle()),d++;for(var c=b[a].particles.length;c--;)0<b[a].particles[c].life?(1===b[a].particles[c].growthType?(h=b[a].particles[c].life/b[a].particles[c].maxLife*b[a].particles[c].width,d=b[a].particles[c].life/b[a].particles[c].maxLife*b[a].particles[c].height):2===b[a].particles[c].growthType?(h=(1-b[a].particles[c].life/b[a].particles[c].maxLife)*b[a].particles[c].width,d=(1-b[a].particles[c].life/b[a].particles[c].maxLife)*b[a].particles[c].height):
(h=b[a].particles[c].width,d=b[a].particles[c].height),void 0===b[a].particles[c].image?(e.fillStyle="rgba("+b[a].particles[c].r+","+b[a].particles[c].g+","+b[a].particles[c].b+", 1)",e.globalAlpha=b[a].particles[c].life/b[a].particles[c].maxLife,s(b[a].particles[c],h,d)):void 0!==b[a].images[b[a].particles[c].image]&&b[a].images[b[a].particles[c].image].loaded&&(e.globalAlpha=b[a].particles[c].life/b[a].particles[c].maxLife,s(b[a].particles[c],h,d,b[a].images[b[a].particles[c].image].image)),b[a].particles[c].x+=
b[a].particles[c].xVelocity,b[a].particles[c].y+=b[a].particles[c].yVelocity,b[a].particles[c].life--):b[a].particles.splice(c,1)}requestAnimationFrame(t,f)}var f=null,e=null,b=[];g.prototype.start=function(){this.emit=!0};g.prototype.stop=function(){this.emit=!1};g.prototype.preloadImage=function(a){var b=new Image,d=this,c=this.images.length;d.images.push({image:b,loaded:!1});this.attachHandler(b,"load",function(){d.images[c].loaded=!0});b.crossOrigin="";b.src=a;return c};g.prototype.attachHandler=
l;return{init:function(a,b,d){f=document.getElementById(a);f.width=b;f.height=d;e=f.getContext("2d");t()},generateEmitter:function(a,b,d,c){return new g(a,b,d,c)},generateParticle:function(a,b,d,c,e,f,g,l,m,n,p,q,r){return new k(a,b,d,c,e,f,g,l,m,n,p,q,r)},addEmitter:function(a,e){void 0!==e&&e&&a.start();b.push(a)},randomNumber:function(a,b,d){void 0===a&&(a=1);void 0===b&&(b=0);void 0===d&&(d=!0);return d?Math.round(Math.random()*a-b):Math.random()*a-b},attachHandler:l}}();